name: PublicCode Check and Update

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository Name
        run: |
          if [[ "${{ github.repository }}" == *".github"* ]]; then
            echo "This workflow cannot be run within .github repositories."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Repository Details
        run: |
          REPO_DETAILS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }})        

      - name: Print GitHub Object
        run: |
          echo "GitHub Object:"
          echo $REPO_DETAILS | jq

      - name: Check and Update publiccode.yaml
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          REPO_DESC="${{ github.event.repository.description }}"
          REPO_URL="${{ github.event.repository.html_url }}"
          REPO_HOMEPAGE="${{ github.event.repository.homepage  }}"
          REPO_TOPICS=${{ github.event.repository.topics }}"
          REPO_LICENSE=${{ github.event.repository.license.key  }}"
          
          ORGANISATION_NAME="${{ github.event.repository.owner.login }}"     
          ORGANISATION_AVATAR="${{ github.event.repository.owner.avatar_url }}"  
          
          if [ ! -f "publiccode.yaml" ]; then
            echo "publiccode.yaml does not exist, creating one."
            touch publiccode.yaml
          fi           

          update_or_append() {
            KEY=$1
            VALUE=$2
            FILE=$3
            if grep -q "^$KEY:" "$FILE"; then
              sed -i "s/^$KEY:.*/$KEY: $VALUE/" "$FILE"
            elif [ "$VALUE" != "null" ]; then
              echo "$KEY: $VALUE" >> "$FILE"
            fi
          }  
          
          update_or_append "name" "$REPO_NAME" "publiccode.yaml"
          update_or_append "description" "$REPO_DESC" "publiccode.yaml"
          update_or_append "url" "$REPO_URL" "publiccode.yaml"
          update_or_append "homepage" "$REPO_HOMEPAGE" "publiccode.yaml"
          update_or_append "topics" "$REPO_TOPICS" "publiccode.yaml"
          update_or_append "license" "$REPO_LICENSE" "publiccode.yaml"
          update_or_append "organisationName" "$ORGANISATION_NAME" "publiccode.yaml"
          update_or_append "organisationAvatar" "$ORGANISATION_AVATAR" "publiccode.yaml"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add publiccode.yaml
          git commit -m "Update publiccode.yaml with repo name and description" || echo "No changes to commit"
          git push