name: PublicCode Check and Update

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository Name
        run: |
          if [[ "${{ github.repository }}" == *".github"* ]]; then
            echo "This workflow cannot be run within .github repositories."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check and Update publiccode.yaml
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          REPO_DESC="${{ github.event.repository.description }}"
          REPO_URL="${{ github.event.repository.html_url }}"
          REPO_HOMEPAGE="${{ github.event.repository.homepage }}"
          REPO_TOPICS="${{ toJson(github.event.repository.topics) }}"
          REPO_LICENSE="${{ github.event.repository.license.key }}"
          REPO_CREATED_AT="${{ github.event.repository.created_at }}"

          ORGANISATION_NAME="${{ github.event.organization.login }}"     
          ORGANISATION_DESCRIPTION="${{ github.event.organization.description }}"     
          ORGANISATION_GITID="${{ github.event.organization.id}}"     
          ORGANISATION_URL="${{ github.event.organization.login }}"     
          ORGANISATION_AVATAR="${{ github.event.organization.avatar_url }}"     
          
          echo "Installing PyYAML..."
          pip install PyYAML

          echo "Updating publiccode.yaml..."
          python - <<END
          import yaml
          import json
          from datetime import datetime

          # Read existing publiccode.yaml
          try:
              with open("publiccode.yaml", "r") as f:
                  data = yaml.safe_load(f)
          except FileNotFoundError:
              data = {}
          
          # Convert created_at to date format
          # created_at_date = datetime.fromisoformat("$REPO_CREATED_AT".replace("Z", "+00:00")).strftime('%Y-%m-%d')
          created_at_date = "$REPO_CREATED_AT"

          # Convert topics JSON string to Python list and then to comma-separated string
          topics_list = json.loads("$REPO_TOPICS")
          topics_str = ', '.join(topics_list)

          # Update or append values
          if "$REPO_NAME" != "null":
              data['name'] = "$REPO_NAME"
          if "$REPO_URL" != "null":
              data['url'] = "$REPO_URL"
          if "$REPO_DESC" != "null":
              data['description'] = "$REPO_DESC"
          if "$REPO_HOMEPAGE" != "null":
              data['homepage'] = "$REPO_HOMEPAGE"
          if topics_str:
              data['topics'] = topics_str
          if "$REPO_LICENSE" != "null":
              data['license'] = "$REPO_LICENSE"

          # Add releaseDate if not present
          if 'releaseDate' not in data:
              data['releaseDate'] = created_at_date

          # Create or update nested 'organisation' array
          if 'organisation' not in data:
              data['organisation'] = {}
          if "$ORGANISATION_NAME" != "null":
              data['organisation']['name'] = "$ORGANISATION_NAME"
          if "$ORGANISATION_AVATAR" != "null":
              data['organisation']['avatar'] = "$ORGANISATION_AVATAR"
          if "$ORGANISATION_URL" != "null":
              data['organisation']['url'] = "$ORGANISATION_URL"
          if "$ORGANISATION_DESCRIPTION" != "null":
              data['organisation']['description'] = "$ORGANISATION_DESCRIPTION"

          # Write updated publiccode.yaml
          with open("publiccode.yaml", "w") as f:
              yaml.safe_dump(data, f)
          END


      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add publiccode.yaml
          git commit -m "${{ github.workflow }}" || echo "No changes to commit"
          git push
